
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"  # Bee debugging port
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - BEE_WATCH=1  # Enable Bee hot reload
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod  # Persist Go modules cache
    networks:
      - app-network
    command: bee run  # Use Bee for development

  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0  # Ensure the version matches Elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=m8kwH52m  # Add password for Kibana if needed
      - KIBANA_ENCRYPTION_KEY=VKLC5lSbqSCaqAtpAfhN8oGX4SeHIVni
    ports:
      - "5601:5601"  # Kibana UI port
    networks:
      - app-network      

volumes:
  elasticsearch-data:
  go-modules:  # Volume for Go modules cache

networks:
  app-network:
    driver: bridge